# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190427_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
