# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-26 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190526_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationoption',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='goods.GoodsSpecification', verbose_name='规格'),
        ),
    ]
